### ISSUE TITLE
Is coordinates validator too strict with longitude?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/fusspot#16]
There are valid reasons for providing longitudes that exceed +/-180, so I worry that our validator is being too strict. 

Should we only enforce that *latitude* is +/-90, since I don't know of any reasons to exceed those limits? Or should we instead remove this validator and just check that we have an array of two numbers?

cc @mapbox/frontend-platform

**Comment by kepta** [comment]
@davidtheclark I think `mapbox-gl-js` complains if the `lat` `lon` exceeds `180` / `90`. Should we keep our validator in sync with how `gl-js` validates coords?

**Comment by davidtheclark** [comment]
@kepta I think that our APIs often do not, though. I believe this is how you'd get directions crossing the antimeridian instead of going around the world to avoid it — right?

**Comment by danswick** [comment]
Interesting question that I will annoyingly respond to with another question: under what circumstances do we anticipate people will use this validator and what is it for? 

- You want to **display something** using your coordinates on a web map (Mapbox GL JS, Leaflet, etc): 
  * for **longitude** can probably be whatever since we use the old "many worlds" trick to handle issues with features that cross the international dateline. However, only some libraries know how to handle lon values >180 or <-180. 
  * for **latitude**: longitude can be assumed to be in the [Spherical Mercator projection](https://epsg.io/3857), which only goes to +/- `85.06` degrees anyway, so we probably want to use _those_ values for validation. 
- You want to make sure your coordinates are valid before you **save some data**. In that case, it's probably best to do a strict validation as-is. 

Perhaps it would be useful to incorporate two types of coordinate validation? One for _displaying stuff_ on a web map and one for _saving data_.

**Comment by davidtheclark** [comment]
@danswick good points. I think that those points illustrate that we shouldn't include this validator by default, because it includes too many assumptions, is not general-purpose enough. If we have a good range validator, that could make it easy enough for consumers to enforce whatever they need, right? (And for mapbox-sdk-js, I suggest we let the APIs themselves handle coordinate validation.)

**Comment by kepta** [comment]
After reading @danswick's points, I too agree that this validator is not really a general purpose validator.

**Comment by danswick** [comment]
> if we have a good range validator, that could make it easy enough for consumers to enforce whatever they need, right? 

This makes sense to me! 

> (And for mapbox-sdk-js, I suggest we let the APIs themselves handle coordinate validation.)

Agreed.
