### ISSUE TITLE
Maybe remove date and coordinates validators, which seem specific to mapbox-sdk-js

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/fusspot#5]
The coordinates validator seems specific to mapbox-sdk-js. 

And although "date" sounds like it might be generic enough, it's actually kind of specific to how we decide to type that for mapbox-sdk-js: anything that can be converted to a `Date` via `new Date(x)`. I'm not sure that's generically useful, since it implies implementation details behind the scenes.

@kepta do you think we should keep either of these?

**Comment by kepta** [comment]
I feel that the format is an established standard since it is used in `geojson`, also a lot of our projects would need this very format, hence it is prudent to keep the validator here.

I agree that the date validator is specific to `mapbox-sdk-js` but I think having a validation library should have some sort of date validation. Maybe we can have a more generic `v.ISODate` validator?

**Comment by davidtheclark** [comment]
> I think having a validation library should have some sort of date validation

If we just want to check whether something is a `Date` object, we could add an `instanceOf` validator and users could specify `instanceOf(Date)`. 

Outside of `Date` instances, though, I don't know of a shared standard that would be worth providing as a default (e.g. ISO string, non-ISO string, number). prop-types gets along without a date validator.

**Comment by kepta** [comment]
I think I get your point about date, lets go ahead and ditch `Date`.
